<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Masuk</name>
   <tag></tag>
   <elementGuidId>54da3cf9-b334-47db-a557-6d00fd52971e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#u_0_5_yC</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[text()='Masuk']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>4f41c90f-ce27-4a59-8f44-75b580537f02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>54b363af-015e-4783-a751-f17e02a81ceb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_42ft _4jy0 _6lth _4jy6 _4jy1 selected _51sy</value>
      <webElementGuid>f2fc3e20-21ec-4320-9f56-7abfa74bdd19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>login</value>
      <webElementGuid>ed9b3433-c8d5-4ba8-b7ec-3ade05d81293</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>royal_login_button</value>
      <webElementGuid>f61a6628-4bcc-4cfd-8777-607108413713</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>ffa7b36f-843f-4232-b881-72766ad1df35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>u_0_5_yC</value>
      <webElementGuid>b8faace1-50b5-4017-9ba7-0167f99bd1f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Masuk</value>
      <webElementGuid>d79f0de8-531e-4e6e-ac9c-1fe59ea7a1fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;u_0_5_yC&quot;)</value>
      <webElementGuid>53567651-6396-478e-9611-b34870b29b2f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='u_0_5_yC']</value>
      <webElementGuid>d3b71a80-6335-42d7-a6eb-4054bbaaea14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='u_0_2_z4']/div[2]/button</value>
      <webElementGuid>e1f3cbb5-193e-4d4e-876a-238fa4bca4fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Facebook membantu Anda terhubung dan berbagi dengan orang-orang dalam kehidupan Anda.'])[1]/following::button[1]</value>
      <webElementGuid>11659369-9f14-416e-b884-8aa0879f63a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lupa Kata Sandi?'])[1]/preceding::button[1]</value>
      <webElementGuid>ed9db2e6-e2a6-4c98-af01-2f06a39a2959</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Masuk']/parent::*</value>
      <webElementGuid>e8c581fe-39a6-47fa-bb80-8ab5f3cd5380</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>c3adbf5f-6b29-4b3d-8169-73d3b99c114c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@name = 'login' and @type = 'submit' and @id = 'u_0_5_yC' and (text() = 'Masuk' or . = 'Masuk')]</value>
      <webElementGuid>450387ee-aed3-4cd0-9feb-c1b990c19d07</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
