<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Facebook_Password</name>
   <tag></tag>
   <elementGuidId>a3ad0f7a-a009-401f-9218-667851cc6f26</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#pass</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='pass']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>31092b4d-e756-4c12-b1b5-00ee54403bee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>63698c75-0ff0-43b6-8b88-4510a0f04ef5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>inputtext _55r1 _6luy _9npi</value>
      <webElementGuid>9d0ed93a-234c-4428-aaab-3ef02c7b8bbb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>pass</value>
      <webElementGuid>f0f0bb98-4f44-488e-b1d4-e1b69abe6a3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pass</value>
      <webElementGuid>f5c1ea92-53a8-483e-a75a-b59b1ccd454b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>royal_pass</value>
      <webElementGuid>92859cb5-1844-4c47-bf91-e0b4d217ddbc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Kata Sandi</value>
      <webElementGuid>f997f79f-35f7-4ead-be6f-a36fcd58182d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Kata Sandi</value>
      <webElementGuid>807d81e0-9a3a-4b52-aed9-1a9c1c13e670</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pass&quot;)</value>
      <webElementGuid>f19e0fa3-a9b4-4d18-8fc2-3bcd1d048cbe</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='pass']</value>
      <webElementGuid>a094e3ad-06fd-4587-9df6-437ecb98bb76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='passContainer']/input</value>
      <webElementGuid>0db13a24-68fd-447b-9ed0-aadab77b3e4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>7a1b9ef8-9d4b-415b-88db-c698e405260f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @name = 'pass' and @id = 'pass' and @placeholder = 'Kata Sandi']</value>
      <webElementGuid>cf5e5daa-23c0-4c9f-a48d-bbc006e566c7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
